name: Build and Release CLI

on:
  push:
    tags:
      - 'v*'  # Run only on version tags like v1.0, v2.0, etc.

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install Dependencies
        run: rustup target add ${{ matrix.target }}

      - name: Run tests
        run: cargo test --verbose

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: cli-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/cdevent
          retention-days: 1

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'  # Only run on tags

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: cli-${{ matrix.target }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cli-x86_64-unknown-linux-gnu
            cli-aarch64-unknown-linux-gnu
            cli-x86_64-apple-darwin
            cli-x86_64-pc-windows-gnu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
